Fix editors list on mobile
debatecore/debateco.re pull request #20
Opened 2024-08-25 13:16 UTC by Mateusz-Dobrzynski

Resolves #18. I decided to display the editors row by row on desktop, too, as I find it more readable regardless of the screen size.

2025-10-15 14:44 UTC, jakubmanczak requested changes
Why does this flip `p` to be `span` and `span` to be `p`?

2025-10-22 06:44 UTC, Mateusz-Dobrzynski commented
To fix an issue with displaying this element in mobile view.

2025-10-22 10:14 UTC, jakubmanczak commented
> To fix an issue with displaying this element in mobile view.

You're [not supposed to do that](https://stackoverflow.com/questions/5545884/can-span-tags-have-any-type-of-tags-inside-them).

It will work because we change what type of elements they are with css, and if we didn't browsers might still accept it so as to not cause trouble, but it's invalid. Let's not do that.

2025-10-22 10:14 UTC, jakubmanczak requested changes
^

2025-10-24 08:04 UTC, jakubmanczak approved these changes

2025-10-24 08:04 UTC, merged